version: '3.1'
services:

  reservacion-deportiva-db:
    image: mysql:8.0
    container_name: reservacion-deportiva-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ceiba
    networks:
    - network_reservacion_deportiva
    
networks:
  network_reservacion_deportiva:
     external: true