version: '3.1'
services:
  reservacion-deportiva-backend-dev:
    image: reservacion-deportiva-backend-dev
    container_name: reservacion-deportiva-backend-dev
    restart: always
    build:
      context: ./
      args:
        - AMBIENTE=dev
    ports:
      - "8081:8080"
    networks:
      - network_reservacion_deportiva

networks:
  network_reservacion_deportiva:
    external: true